# Use Shopify Ruby style
inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/MethodCallWithArgsParentheses:
  Enabled: false
